In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import r2_score
from sklearn import metrics



import matplotlib.pyplot as plt
import seaborn as sns

# import warnings filter
from warnings import simplefilter
# ignore all future warnings
simplefilter(action='ignore', category=FutureWarning)

In [3]:
file = pd.read_csv('../framinghan_function/framingham-score-risk.csv')
df   = pd.DataFrame(file)
df

age  gender   BMI  ap_hi  ap_lo  cholesterol  gluc  smoke  alco  \
0      50.0       2  22.0    110     80            1     1      0     0   
1      55.0       1  35.0    140     90            3     1      0     0   
2      52.0       1  24.0    130     70            3     1      0     0   
3      48.0       2  29.0    150    100            1     1      0     0   
4      48.0       1  23.0    100     60            1     1      0     0   
...     ...     ...   ...    ...    ...          ...   ...    ...   ...   
69995  53.0       2  27.0    120     80            1     1      1     0   
69996  62.0       1  50.0    140     90            2     2      0     0   
69997  52.0       2  31.0    180     90            3     1      0     1   
69998  61.0       1  27.0    135     80            1     2      0     0   
69999  56.0       1  25.0    120     80            2     1      0     0   

       active  cardio  fram_score  risk  risk_group  
0           1       0           3  0.05           2  
1           1       1          12  0.13           4  
2           0       1           9  0.08           3  
3           1       1           5  0.08           3  
4           0       0           0  0.02           1  
...       ...     ...         ...   ...         ...  
69995       1       0           5  0.08           3  
69996       1       1          15  0.20           5  
69997       0       1           9  0.20           5  
69998       0       1          12  0.13           4  
69999       1       0           8  0.07           3  

[70000 rows x 14 columns]

In [4]:
df = df.drop(columns = ['ap_hi', 'ap_lo', 'cholesterol', 'cardio', 'fram_score', 'risk'])

In [5]:
df

age  gender   BMI  gluc  smoke  alco  active  risk_group
0      50.0       2  22.0     1      0     0       1           2
1      55.0       1  35.0     1      0     0       1           4
2      52.0       1  24.0     1      0     0       0           3
3      48.0       2  29.0     1      0     0       1           3
4      48.0       1  23.0     1      0     0       0           1
...     ...     ...   ...   ...    ...   ...     ...         ...
69995  53.0       2  27.0     1      1     0       1           3
69996  62.0       1  50.0     2      0     0       1           5
69997  52.0       2  31.0     1      0     1       0           5
69998  61.0       1  27.0     2      0     0       0           4
69999  56.0       1  25.0     1      0     0       1           3

[70000 rows x 8 columns]

In [6]:
X = df.drop(["risk_group"], axis=1)
y = df["risk_group"]

scaler = MinMaxScaler()
X = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
                                X, y, test_size=0.2,
                                    random_state=158)

In [9]:
# The n_neighbours with the best value was k = 29

model = KNeighborsClassifier(algorithm='brute',leaf_size= 1,n_jobs= -1,
                             n_neighbors= 25,weights= 'uniform')
clf = model.fit(X_train, y_train)
%time y_pred = clf.predict(X_test)

print("Accuracy:",metrics.accuracy_score(y_pred,y_test))
print("Confusion Metrix:\n",metrics.confusion_matrix(y_pred,y_test))

Wall time: 27.1 s
Accuracy: 0.6114285714285714
Confusion Metrix:
 [[2070  387   82   18    0]
 [ 363 1830  887  234   28]
 [  49  530 2777 1246  208]
 [   1   69  609 1208  325]
 [   2    4   89  309  675]]


# PREDICTING SPAIN MODEL

In [15]:
file_spain = pd.read_csv('../coutry_model/country-model-v01.csv')
df_es      = pd.DataFrame(file_spain)
df_es      = df_es.drop(columns = ['Unnamed: 0'])
df_es.head(3)

age  gender       BMI  gluc  smoke  alco  active  risk_group
0   30       1  19.99596     1      0     1       1           0
1   30       1  19.99596     1      1     1       1           0
2   30       1  19.99596     1      0     1       1           0

In [23]:
df_es.sample(5)

age  gender        BMI  gluc  smoke  alco  active  risk_group
828492   59       2  25.404160     1      1     1       1           0
530876   34       2  17.356998     1      1     0       0           0
690731   47       2  25.404160     1      1     1       1           0
15879    31       1  17.524374     1      0     1       0           0
434752   70       1  17.524374     1      0     0       1           0

In [10]:
df_es.shape

(1000000, 8)

In [11]:
X_es = df_es.drop(["risk_group"], axis=1)
y_es = df_es["risk_group"]

scaler = MinMaxScaler()
X_es = scaler.fit_transform(X_es)

%time y_es_pred = clf.predict(X_es)

Wall time: 32min 58s


In [12]:
y_es_pred
len(y_es_pred)

1000000

In [13]:
df_es.risk_group = y_es_pred

In [14]:
df_es

age  gender        BMI  gluc  smoke  alco  active  risk_group
0        30       1  19.995960     1      0     1       1           1
1        30       1  19.995960     1      1     1       1           1
2        30       1  19.995960     1      0     1       1           1
3        30       1  17.524374     1      0     1       0           1
4        30       1  19.995960     1      0     1       0           1
...     ...     ...        ...   ...    ...   ...     ...         ...
999995   80       2  24.240528     1      0     1       0           4
999996   80       2  17.356998     1      1     0       1           5
999997   80       2  25.404160     1      1     0       1           5
999998   80       2  30.831786     3      1     0       1           5
999999   80       2  17.356998     1      1     0       1           5

[1000000 rows x 8 columns]

In [15]:
df_es.risk_group.value_counts()


1    357132
2    188360
3    176858
5    155688
4    121962
Name: risk_group, dtype: int64

In [16]:
df_es.to_csv('knn-5p-results.csv', index=False)

In [11]:
file_spain = pd.read_csv('knn-5p-results.csv')
df_es   = pd.DataFrame(file_spain)
df_es.sample(5)

age  gender        BMI  gluc  smoke  alco  active  risk_group
668984   45       2  17.356998     1      1     1       0           2
707108   48       2  30.831786     1      1     0       1           4
550456   36       2  24.240528     1      1     0       1           2
663577   45       2  24.240528     1      1     1       0           2
434189   70       1  17.524374     1      0     0       1           3

In [12]:
df_es.sample(5)

age  gender        BMI  gluc  smoke  alco  active  risk_group
459037   74       1  17.524374     1      0     0       1           3
755086   52       2  25.404160     1      1     1       0           4
107097   40       1  17.524374     1      1     0       1           1
863370   62       2  17.356998     1      0     0       0           2
255058   51       1  17.524374     1      1     0       0           1