In [9]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import classification_report
from sklearn.calibration import CalibratedClassifierCV
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest

from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

from sklearn.metrics import confusion_matrix
from sklearn.metrics import r2_score
from sklearn import metrics
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score

import matplotlib.pyplot as plt
import seaborn as sns

# import warnings filter
from warnings import simplefilter
# ignore all future warnings
simplefilter(action='ignore', category=FutureWarning)

from sklearn import linear_model
from sklearn import svm

In [10]:
file = pd.read_csv('../framinghan_function/framingham-score-risk.csv')
df   = pd.DataFrame(file)

In [11]:
df

age  gender   BMI  ap_hi  ap_lo  cholesterol  gluc  smoke  alco  \
0      50.0       2  22.0    110     80            1     1      0     0   
1      55.0       1  35.0    140     90            3     1      0     0   
2      52.0       1  24.0    130     70            3     1      0     0   
3      48.0       2  29.0    150    100            1     1      0     0   
4      48.0       1  23.0    100     60            1     1      0     0   
...     ...     ...   ...    ...    ...          ...   ...    ...   ...   
69995  53.0       2  27.0    120     80            1     1      1     0   
69996  62.0       1  50.0    140     90            2     2      0     0   
69997  52.0       2  31.0    180     90            3     1      0     1   
69998  61.0       1  27.0    135     80            1     2      0     0   
69999  56.0       1  25.0    120     80            2     1      0     0   

       active  cardio  fram_score  risk  risk_group  
0           1       0           3  0.05           2  
1           1       1          12  0.13           4  
2           0       1           9  0.08           3  
3           1       1           5  0.08           3  
4           0       0           0  0.02           1  
...       ...     ...         ...   ...         ...  
69995       1       0           5  0.08           3  
69996       1       1          15  0.20           5  
69997       0       1           9  0.20           5  
69998       0       1          12  0.13           4  
69999       1       0           8  0.07           3  

[70000 rows x 14 columns]

In [12]:
df = df.drop(columns = ['ap_hi', 'ap_lo', 'cholesterol', 'cardio', 'fram_score', 'risk'])

In [13]:
df

age  gender   BMI  gluc  smoke  alco  active  risk_group
0      50.0       2  22.0     1      0     0       1           2
1      55.0       1  35.0     1      0     0       1           4
2      52.0       1  24.0     1      0     0       0           3
3      48.0       2  29.0     1      0     0       1           3
4      48.0       1  23.0     1      0     0       0           1
...     ...     ...   ...   ...    ...   ...     ...         ...
69995  53.0       2  27.0     1      1     0       1           3
69996  62.0       1  50.0     2      0     0       1           5
69997  52.0       2  31.0     1      0     1       0           5
69998  61.0       1  27.0     2      0     0       0           4
69999  56.0       1  25.0     1      0     0       1           3

[70000 rows x 8 columns]

In [14]:
X = df.drop(["risk_group"], axis=1)
y = df["risk_group"]

scaler = MinMaxScaler()
X = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

In [23]:
# Import the model we are using
from sklearn.ensemble import RandomForestRegressor

# Instantiate model with 1000 decision trees

#First iteration of the rf
#rf = RandomForestRegressor(n_estimators = 100, random_state = 42)

rf = RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=80, max_features=3, max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=5,
                      min_samples_split=12, min_weight_fraction_leaf=0.0,
                      n_estimators=200, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)


# Train the model on training data
rf.fit(X_train, y_train)


#Results obtained after calculating 'grid_search.best_estimator_'
# RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
#                       max_depth=80, max_features=3, max_leaf_nodes=None,
#                       max_samples=None, min_impurity_decrease=0.0,
#                       min_impurity_split=None, min_samples_leaf=5,
#                       min_samples_split=12, min_weight_fraction_leaf=0.0,
#                       n_estimators=200, n_jobs=None, oob_score=False,
#                       random_state=None, verbose=0, warm_start=False)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=80, max_features=3, max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=5,
                      min_samples_split=12, min_weight_fraction_leaf=0.0,
                      n_estimators=200, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [46]:
X = df.drop(["risk_group"], axis=1)
y = df["risk_group"]

scaler = MinMaxScaler()
X = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [53]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report

for i in range(1, 20, 2):
    rf = RandomForestRegressor(max_depth=i)
    clf = rf.fit(X_train, y_train)

    y_pred = np.around(clf.predict(X_test))
    
    print(i)
    print(accuracy_score(y_test, y_pred))
    print(f1_score(y_test, y_pred, average='macro'))
    print('################################################')

1
0.3467142857142857
0.19445749012196079
################################################
3
0.4878571428571429
0.43918873734215824
################################################
5
0.5377857142857143
0.5513886000008862
################################################
7
0.5898571428571429
0.5979170736721162
################################################
9
0.588
0.5952397841337544
################################################
11
0.5860714285714286
0.5920174379261841
################################################
13
0.5802142857142857
0.5860787586848587
################################################
15
0.5766428571428571
0.5805113116163128
################################################
17
0.5742857142857143
0.5776483652890507
################################################
19
0.5743571428571429
0.5779909015324638
################################################


# Let's evaluate the best number of parameters.

Inspiration from: https://www.kaggle.com/mayu0116/hyper-parameters-tuning-of-dtree-rf-svm-knn

In [8]:
#With Hyper Parameters Tuning
#2-2,Randomforest
#importing modules
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
#making the instance
model=RandomForestClassifier()
#hyper parameters set
params = {'criterion':['gini','entropy'],
          'n_estimators':[100, 200, 300, 1000],
          'min_samples_leaf':[3, 4, 5],
          'min_samples_split':[8,10,12], 
          'random_state':[123],
          'n_jobs':[-1]}
#Making models with hyper parameters sets
model1 = GridSearchCV(model, param_grid=params, n_jobs=-1)
#learning
model1.fit(X_train,y_train)
#The best hyper parameters set
print("Best Hyper Parameters:\n",model1.best_params_)
#Prediction
prediction= np.around(model1.predict(X_test))
#importing the metrics module
from sklearn import metrics
#evaluation(Accuracy)
print("Accuracy:",metrics.accuracy_score(prediction,y_test))
#evaluation(Confusion Metrix)
print("Confusion Metrix:\n",metrics.confusion_matrix(prediction,y_test))



Best Hyper Parameters:
 {'criterion': 'entropy', 'min_samples_leaf': 5, 'min_samples_split': 12, 'n_estimators': 1000, 'n_jobs': -1, 'random_state': 123}
Accuracy: 0.6038571428571429
Confusion Metrix:
 [[2068  384   70   11    0]
 [ 354 1793  861  181   22]
 [  70  593 2683 1197  211]
 [   1   92  700 1202  353]
 [   0    3   91  352  708]]


In [15]:
f = open("rfr-5p-best-score", "a")
print("Best Hyper Parameters:\n",model1.best_params_, file=f)
print("Accuracy:",metrics.accuracy_score(prediction,y_test), file=f)
print("Confusion Metrix:\n",metrics.confusion_matrix(prediction,y_test), file=f)
f.close()

In [14]:
from sklearn.model_selection import GridSearchCV
# Create the parameter grid based on the results of random search 

param_grid = {
    'bootstrap': [True],
    'max_depth': [80, 90, 100, 110],
    'max_features': [2, 3],
    'min_samples_leaf': [3, 4, 5],
    'min_samples_split': [8, 10, 12],
    'n_estimators': [100, 200, 300, 1000]
}# Create a based model
rf = RandomForestRegressor()# Instantiate the grid search model
grid_search = GridSearchCV(estimator = rf, param_grid = param_grid, 
                          cv = 3, n_jobs = -1, verbose = 2)

In [15]:
X_train, X_test, y_train, y_test 

# Fit the grid search to the data
grid_search.fit(X_train, y_train)

grid_search.best_params_

best_grid = grid_search.best_estimator_

Fitting 3 folds for each of 288 candidates, totalling 864 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:   58.8s
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:  5.7min
[Parallel(n_jobs=-1)]: Done 349 tasks      | elapsed: 14.8min
[Parallel(n_jobs=-1)]: Done 632 tasks      | elapsed: 26.9min
[Parallel(n_jobs=-1)]: Done 864 out of 864 | elapsed: 36.7min finished


In [16]:
best_grid

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=80, max_features=3, max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=5,
                      min_samples_split=12, min_weight_fraction_leaf=0.0,
                      n_estimators=200, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)